Repository bowman-lab/enspara, pull requests merged in 2018-12, with the labels that each got.

#138 Updates and Beautification of Docs
  docs/source/_modules/enspara.apps.rst
  docs/source/_modules/enspara.cards.rst
  docs/source/_modules/enspara.cluster.rst
  docs/source/_modules/enspara.geometry.rst
  docs/source/_modules/enspara.mpi.rst
  docs/source/_modules/enspara.msm.rst
  docs/source/_modules/enspara.rst
  docs/source/_modules/enspara.util.rst
  docs/source/apps.rst
  docs/source/clustering.rst
  docs/source/conf.py
  docs/source/index.rst
  enspara/apps/__init__.py
  enspara/apps/cluster.py
  enspara/apps/implied_timescales.py
  enspara/apps/reassign.py
  enspara/apps/util.py
  enspara/cards/cards.py
  enspara/cards/disorder.py
  enspara/cards/featurizers.py
  enspara/cluster/kcenters.py
  enspara/cluster/kmedoids.py
  enspara/info_theory/mutual_info.py
  enspara/msm/bace.py
  enspara/msm/msm.py
  enspara/msm/synthetic_data.py
  enspara/tpt/core.py
  enspara/util/load.py
Labels: awaiting-review, docs

#146 Fix installation instructions to point to readthedocs
  README.md
Labels: docs

#147 Add entry point script.
  enspara/apps/cluster.py
  enspara/apps/implied_timescales.py
  enspara/apps/main.py
  setup.py
Labels: awaiting-review, enhancement

#143 Create ra module
  enspara/ra/__init__.py
  enspara/ra/ra.py
  enspara/util/array.py
Labels: awaiting-review, enhancement

#142 Remove mpi4py import protection
  enspara/mpi/__init__.py
Labels: awaiting-review, bug

#148 Tutorial docs
  docs/source/_modules/enspara.msm.rst
  docs/source/_modules/enspara.rst
  docs/source/cli.rst
  docs/source/clustering.rst
  docs/source/cookbook.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/pocket-detection.rst
  docs/source/transition-path-theory.rst
  docs/source/tutorial/analysis.rst
  docs/source/tutorial/clustering-trajectories.rst
  docs/source/tutorial/fitting.rst
  docs/source/tutorial/hbond-free-energy.svg
  docs/source/tutorial/hbond-mi.svg
  docs/source/tutorial/mean-hbond-energy.svg
  docs/source/tutorial/tutorial.rst
  enspara/cards/__init__.py
  enspara/cluster/__init__.py
  enspara/exception.py
  enspara/geometry/__init__.py
  enspara/info_theory/__init__.py
  enspara/mpi/__init__.py
  enspara/msm/__init__.py
  enspara/tpt/__init__.py
  enspara/util/__init__.py
Labels: docs

#145 Build triangle inequality use.
  enspara/cluster/kcenters.py
  enspara/test/test_cluster.py
Labels: awaiting-review, enhancement

#144 Add --cluster-iterations, fix bugs.
  enspara/apps/cluster.py
  enspara/cluster/hybrid.py
  enspara/cluster/kcenters.py
  enspara/test/test_apps_cluster.py
Labels: awaiting-review, bug, enhancement
