Repository bowman-lab/enspara, pull requests merged in 2019-04, with the labels that each got.

#165 Weighted mi check
  enspara/info_theory/mutual_info.py
Labels: bug

#141 RaggedArray save/load update
  enspara/ra/ra.py
  enspara/test/test_util.py
  enspara/util/array.py
Labels: awaiting-review, enhancement

#166 Parallel h5 load
  enspara/apps/cluster.py
  enspara/mpi/io.py
  enspara/ra/ra.py
  enspara/test/test_apps_cluster_mpi.py
  enspara/test/test_mpi_io.py
  enspara/test/test_ra.py
Labels: enhancement

#162 Add CARDS tutorial to docs. Other docs improvements.
  .circleci/config.yml
  docs/source/cards.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/tutorial/analysis.rst
  enspara/cards/__init__.py
  enspara/cards/cards.py
Labels: docs

#168 MPI updates
  enspara/apps/cluster.py
  enspara/cluster/hybrid.py
  enspara/cluster/kcenters.py
  enspara/cluster/kmedoids.py
  enspara/mpi/__init__.py
  enspara/mpi/io.py
  enspara/mpi/ops.py
  enspara/test/test_apps_cluster_mpi.py
  enspara/test/test_cluster.py
  enspara/test/test_mpi_io.py
  enspara/test/test_mpi_ops.py
  enspara/test/test_msm_bootstrap.py
Labels: awaiting-review, bug, enhancement

#169 Elaborate SharedArray OOM error
  enspara/test/test_mutual_info.py
  enspara/util/load.py
Labels: enhancement
