Repository bowman-lab/enspara, pull requests merged in 2019-03, with the labels that each got.

#160 pocket calculation update
  enspara/geometry/pockets.py
Labels: enhancement

#159 Performance improvements to weighted_mi
  enspara/info_theory/mutual_info.py
Labels: awaiting-review, enhancement

#157 Change rotamer.py to spaces, add ability to use zero buffer width.
  enspara/geometry/rotamer.py
Labels: enhancement

#163 Reraise memory error in loading features, improve output file warnings.
  .circleci/config.yml
  enspara/apps/cluster.py
Labels: awaiting-review, bug
